#! /usr/bin/python
# This script was automatically generated by setup.py
# This can not be used from within virtualenv
if __name__ == '__main__':
    from ConsumerCheck import cc_start
    cc_start.main()
